In [3]:
"""
gate_inputs = math_ops.matmul(
        array_ops.concat([inputs, h], 1), self._kernel) #input(?,28) h (?,256) kernel(284,1024) 
    gate_inputs = nn_ops.bias_add(gate_inputs, self._bias) #(?,1024)
    LSTM中有一段将input和隐层按第二维度拼接
"""
import tensorflow as tf
from tensorflow.python.ops import array_ops
a = tf.constant([[1,12,8,12],[3,4,6,7]])
b = tf.constant([[10,20,3,33,123],[30,40,50,12,12]])
ab = array_ops.concat([a,b],1) #[m,n],[m,k] ,concat: [m,a+b]
with tf.Session() as sess:
    print(ab)
    print(ab.eval())
    
    """
    Tensor("concat:0", shape=(2, 9), dtype=int32)
[[  1  12   8  12  10  20   3  33 123]
 [  3   4   6   7  30  40  50  12  12]]
    
    """

Tensor("concat:0", shape=(2, 9), dtype=int32)
[[  1  12   8  12  10  20   3  33 123]
 [  3   4   6   7  30  40  50  12  12]]
